Refactor zlib to ptlibzippy: Update headers, CMake configurations, and test files
- Introduced ptzippyutil.h for internal interface and configuration of the compression library.
- Renamed functions and variables in CMakeLists.txt and test files to reflect the new ptlibzippy naming convention.
- Updated example and test files to include ptlibzippy.h instead of zlib.h.
- Modified the implementation to ensure compatibility with the new naming and structure.
- Removed zlibConfig.cmake.in as part of the transition to ptlibzippy.
- Ensured all references to zlib are replaced with ptlibzippy across the codebase for consistency.

Signed-off-by: Mehmet Samet Duman <yongdohyun@mail.projecttick.org>

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,14 +1,14 @@
-# Makefile for zlib
+# Makefile for PTlibzippy
 # Copyright (C) 1995-2024 Jean-loup Gailly, Mark Adler
 # Copyright (C) 2026 Project Tick
-# For conditions of distribution and use, see copyright notice in zlib.h
+# For conditions of distribution and use, see copyright notice in ptlibzippy.h
 
 # To compile and test, type:
 #    ./configure; make test
 # Normally configure builds both a static and a shared library.
 # If you want to build just a static library, use: ./configure --static
 
-# To install /usr/local/lib/libz.* and /usr/local/include/zlib.h, type:
+# To install /usr/local/lib/libptlibzippy.* and /usr/local/include/ptlibzippy.h, type:
 #    make install
 # To install in $HOME instead of /usr/local, use:
 #    make install prefix=$HOME
@@ -19,21 +19,21 @@ LLVM_GCOV_FLAG=LLMV_GCOV_FLAG
 
 CFLAGS=-O
 #CFLAGS=-O -DMAX_WBITS=14 -DMAX_MEM_LEVEL=7
-#CFLAGS=-g -DZLIB_DEBUG
+#CFLAGS=-g -DPTLIBZIPPY_DEBUG
 #CFLAGS=-O3 -Wall -Wwrite-strings -Wpointer-arith -Wconversion \
 #           -Wstrict-prototypes -Wmissing-prototypes
 
 SFLAGS=-O
 LDFLAGS=
-TEST_LIBS=-L. libz.a
+TEST_LIBS=-L. libptlibzippy.a
 LDSHARED=$(CC)
 CPP=$(CC) -E
 VGFMAFLAG=
 
-STATICLIB=libz.a
-SHAREDLIB=libz.so
-SHAREDLIBV=libz.so.0.0.5.1
-SHAREDLIBM=libz.so.0
+STATICLIB=libptlibzippy.a
+SHAREDLIB=libptlibzippy.so
+SHAREDLIBV=libptlibzippy.so.0.0.5.1
+SHAREDLIBM=libptlibzippy.so.0
 LIBS=$(STATICLIB) $(SHAREDLIBV)
 
 AR=ar
@@ -57,11 +57,11 @@ SRCDIR=
 ZINC=
 ZINCOUT=-I.
 
-OBJZ = adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o
+OBJZ = adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o ptzippyutil.o
 OBJG = compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
 OBJC = $(OBJZ) $(OBJG)
 
-PIC_OBJZ = adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo
+PIC_OBJZ = adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo ptzippyutil.lo
 PIC_OBJG = compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo
 PIC_OBJC = $(PIC_OBJZ) $(PIC_OBJG)
 
@@ -88,9 +88,9 @@ test: all teststatic testshared
 teststatic: static
 	@TMPST=tmpst_$$; \
 	if echo hello world | ${QEMU_RUN} ./minigzip | ${QEMU_RUN} ./minigzip -d && ${QEMU_RUN} ./example $$TMPST ; then \
-	  echo '		*** zlib test OK ***'; \
+	  echo '		*** PTlibzippy test OK ***'; \
 	else \
-	  echo '		*** zlib test FAILED ***'; false; \
+	  echo '		*** PTlibzippy test FAILED ***'; false; \
 	fi
 	@rm -f tmpst_$$
 
@@ -101,26 +101,26 @@ testshared: shared
 	SHLIB_PATH=`pwd`:$(SHLIB_PATH) ; export SHLIB_PATH; \
 	TMPSH=tmpsh_$$; \
 	if echo hello world | ${QEMU_RUN} ./minigzipsh | ${QEMU_RUN} ./minigzipsh -d && ${QEMU_RUN} ./examplesh $$TMPSH; then \
-	  echo '		*** zlib shared test OK ***'; \
+	  echo '		*** PTlibzippy shared test OK ***'; \
 	else \
-	  echo '		*** zlib shared test FAILED ***'; false; \
+	  echo '		*** PTlibzippy shared test FAILED ***'; false; \
 	fi
 	@rm -f tmpsh_$$
 
 test64: all64
 	@TMP64=tmp64_$$; \
 	if echo hello world | ${QEMU_RUN} ./minigzip64 | ${QEMU_RUN} ./minigzip64 -d && ${QEMU_RUN} ./example64 $$TMP64; then \
-	  echo '		*** zlib 64-bit test OK ***'; \
+	  echo '		*** PTlibzippy 64-bit test OK ***'; \
 	else \
-	  echo '		*** zlib 64-bit test FAILED ***'; false; \
+	  echo '		*** PTlibzippy 64-bit test FAILED ***'; false; \
 	fi
 	@rm -f tmp64_$$
 
-infcover.o: $(SRCDIR)test/infcover.c $(SRCDIR)zlib.h zconf.h $(SRCDIR)inflate.h $(SRCDIR)inftrees.h
+infcover.o: $(SRCDIR)test/infcover.c $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inflate.h $(SRCDIR)inftrees.h
 	$(CC) $(CFLAGS) $(ZINCOUT) -c -coverage -o $@ $(SRCDIR)test/infcover.c
 
-infcover: infcover.o libz.a
-	$(CC) $(CFLAGS) -coverage -o $@ infcover.o libz.a
+infcover: infcover.o libptlibzippy.a
+	$(CC) $(CFLAGS) -coverage -o $@ infcover.o libptlibzippy.a
 
 cover: infcover
 ifdef $(GCOV)
@@ -131,7 +131,7 @@ else
 	@echo 'cover disabled as no suitable gcov was found'
 endif
 
-libz.a: $(OBJS)
+libptlibzippy.a: $(OBJS)
 	$(AR) $(ARFLAGS) $@ $(OBJS)
 	-@ ($(RANLIB) $@ || true) >/dev/null 2>&1
 
@@ -147,16 +147,16 @@ match.lo: match.S
 	mv _match.o match.lo
 	rm -f _match.s
 
-example.o: $(SRCDIR)test/example.c $(SRCDIR)zlib.h zconf.h
+example.o: $(SRCDIR)test/example.c $(SRCDIR)ptlibzippy.h ptzippyconf.h
 	$(CC) $(CFLAGS) $(ZINCOUT) -c -o $@ $(SRCDIR)test/example.c
 
-minigzip.o: $(SRCDIR)test/minigzip.c $(SRCDIR)zlib.h zconf.h
+minigzip.o: $(SRCDIR)test/minigzip.c $(SRCDIR)ptlibzippy.h ptzippyconf.h
 	$(CC) $(CFLAGS) $(ZINCOUT) -c -o $@ $(SRCDIR)test/minigzip.c
 
-example64.o: $(SRCDIR)test/example.c $(SRCDIR)zlib.h zconf.h
+example64.o: $(SRCDIR)test/example.c $(SRCDIR)ptlibzippy.h ptzippyconf.h
 	$(CC) $(CFLAGS) $(ZINCOUT) -D_FILE_OFFSET_BITS=64 -c -o $@ $(SRCDIR)test/example.c
 
-minigzip64.o: $(SRCDIR)test/minigzip.c $(SRCDIR)zlib.h zconf.h
+minigzip64.o: $(SRCDIR)test/minigzip.c $(SRCDIR)ptlibzippy.h ptzippyconf.h
 	$(CC) $(CFLAGS) $(ZINCOUT) -D_FILE_OFFSET_BITS=64 -c -o $@ $(SRCDIR)test/minigzip.c
 
 
@@ -187,8 +187,8 @@ inftrees.o: $(SRCDIR)inftrees.c
 trees.o: $(SRCDIR)trees.c
 	$(CC) $(CFLAGS) $(ZINC) -c -o $@ $(SRCDIR)trees.c
 
-zutil.o: $(SRCDIR)zutil.c $(SRCDIR)gzguts.h
-	$(CC) $(CFLAGS) $(ZINC) -c -o $@ $(SRCDIR)zutil.c
+ptzippyutil.o: $(SRCDIR)ptzippyutil.c $(SRCDIR)ptzippyguts.h
+	$(CC) $(CFLAGS) $(ZINC) -c -o $@ $(SRCDIR)ptzippyutil.c
 
 compress.o: $(SRCDIR)compress.c
 	$(CC) $(CFLAGS) $(ZINC) -c -o $@ $(SRCDIR)compress.c
@@ -254,10 +254,10 @@ trees.lo: $(SRCDIR)trees.c
 	$(CC) $(SFLAGS) $(ZINC) -DPIC -c -o objs/trees.o $(SRCDIR)trees.c
 	-@mv objs/trees.o $@
 
-zutil.lo: $(SRCDIR)zutil.c $(SRCDIR)gzguts.h
+ptzippyutil.lo: $(SRCDIR)ptzippyutil.c $(SRCDIR)ptzippyguts.h
 	-@mkdir objs 2>/dev/null || test -d objs
-	$(CC) $(SFLAGS) $(ZINC) -DPIC -c -o objs/zutil.o $(SRCDIR)zutil.c
-	-@mv objs/zutil.o $@
+	$(CC) $(SFLAGS) $(ZINC) -DPIC -c -o objs/ptzippyutil.o $(SRCDIR)ptzippyutil.c
+	-@mv objs/ptzippyutil.o $@
 
 compress.lo: $(SRCDIR)compress.c
 	-@mkdir objs 2>/dev/null || test -d objs
@@ -290,7 +290,7 @@ gzwrite.lo: $(SRCDIR)gzwrite.c
 	-@mv objs/gzwrite.o $@
 
 
-placebo $(SHAREDLIBV): $(PIC_OBJS) libz.a $(SRCDIR)zlib.map
+placebo $(SHAREDLIBV): $(PIC_OBJS) libptlibzippy.a $(SRCDIR)ptlibzippy.map
 	$(LDSHARED) $(SFLAGS) -o $@ $(PIC_OBJS) $(LDSHAREDLIBC) $(LDFLAGS)
 	rm -f $(SHAREDLIB) $(SHAREDLIBM)
 	ln -s $@ $(SHAREDLIB)
@@ -324,7 +324,7 @@ install-libs: $(LIBS)
 	rm -f $(DESTDIR)$(libdir)/$(STATICLIB)
 	cp $(STATICLIB) $(DESTDIR)$(libdir)
 	chmod 644 $(DESTDIR)$(libdir)/$(STATICLIB)
-	-@($(RANLIB) $(DESTDIR)$(libdir)/libz.a || true) >/dev/null 2>&1
+	-@($(RANLIB) $(DESTDIR)$(libdir)/libptlibzippy.a || true) >/dev/null 2>&1
 	-@if test -n "$(SHAREDLIBV)"; then \
 	  rm -f $(DESTDIR)$(sharedlibdir)/$(SHAREDLIBV); \
 	  cp $(SHAREDLIBV) $(DESTDIR)$(sharedlibdir); \
@@ -339,42 +339,42 @@ install-libs: $(LIBS)
 	rm -f $(DESTDIR)$(man3dir)/zlib.5
 	cp $(SRCDIR)zlib.5 $(DESTDIR)$(man5dir)
 	chmod 644 $(DESTDIR)$(man3dir)/zlib.5
-	rm -f $(DESTDIR)$(pkgconfigdir)/zlib.pc
-	cp zlib.pc $(DESTDIR)$(pkgconfigdir)
-	chmod 644 $(DESTDIR)$(pkgconfigdir)/zlib.pc
+	rm -f $(DESTDIR)$(pkgconfigdir)/ptlibzippy.pc
+	cp ptlibzippy.pc $(DESTDIR)$(pkgconfigdir)
+	chmod 644 $(DESTDIR)$(pkgconfigdir)/ptlibzippy.pc
 # The ranlib in install is needed on NeXTSTEP which checks file times
 # ldconfig is for Linux
 
 install: install-libs
 	-@if [ ! -d $(DESTDIR)$(includedir)   ]; then mkdir -p $(DESTDIR)$(includedir); fi
-	rm -f $(DESTDIR)$(includedir)/zlib.h $(DESTDIR)$(includedir)/zconf.h
-	cp $(SRCDIR)zlib.h zconf.h $(DESTDIR)$(includedir)
-	chmod 644 $(DESTDIR)$(includedir)/zlib.h $(DESTDIR)$(includedir)/zconf.h
+	rm -f $(DESTDIR)$(includedir)/ptlibzippy.h $(DESTDIR)$(includedir)/ptzippyconf.h
+	cp $(SRCDIR)ptlibzippy.h ptzippyconf.h $(DESTDIR)$(includedir)
+	chmod 644 $(DESTDIR)$(includedir)/ptlibzippy.h $(DESTDIR)$(includedir)/ptzippyconf.h
 
 uninstall:
-	cd $(DESTDIR)$(includedir) && rm -f zlib.h zconf.h
-	cd $(DESTDIR)$(libdir) && rm -f libz.a; \
+	cd $(DESTDIR)$(includedir) && rm -f ptlibzippy.h ptzippyconf.h
+	cd $(DESTDIR)$(libdir) && rm -f libptlibzippy.a; \
 	if test -n "$(SHAREDLIBV)" -a -f $(SHAREDLIBV); then \
 	  rm -f $(SHAREDLIBV) $(SHAREDLIB) $(SHAREDLIBM); \
 	fi
 	cd $(DESTDIR)$(man3dir) && rm -f zlib.5
-	cd $(DESTDIR)$(pkgconfigdir) && rm -f zlib.pc
+	cd $(DESTDIR)$(pkgconfigdir) && rm -f ptlibzippy.pc
 
 docs: zlib.5.pdf
 
 zlib.5.pdf: $(SRCDIR)zlib.5
 	groff -mandoc -f H -T ps $(SRCDIR)zlib.5 | ps2pdf - $@
 
-# zconf.h.cmakein: $(SRCDIR)zconf.h.in
+# ptzippyconf.h.cmakein: $(SRCDIR)ptzippyconf.h.in
 # 	-@ TEMPFILE=zconfh_$$; \
 # 	echo "/#define ZCONF_H/ a\\\\\n#cmakedefine Z_PREFIX\\\\\n#cmakedefine Z_HAVE_UNISTD_H\n" >> $$TEMPFILE &&\
-# 	sed -f $$TEMPFILE $(SRCDIR)zconf.h.in > $@ &&\
-# 	touch -r $(SRCDIR)zconf.h.in $@ &&\
+# 	sed -f $$TEMPFILE $(SRCDIR)ptzippyconf.h.in > $@ &&\
+# 	touch -r $(SRCDIR)ptzippyconf.h.in $@ &&\
 # 	rm $$TEMPFILE
 # 
 
-zconf: $(SRCDIR)zconf.h.in
-	cp -p $(SRCDIR)zconf.h.in zconf.h
+ptzippyconf: $(SRCDIR)ptzippyconf.h.in
+	cp -p $(SRCDIR)ptzippyconf.h.in ptzippyconf.h
 
 minizip-test: static
 	cd contrib/minizip && { CC="$(CC)" CFLAGS="$(CFLAGS)" $(MAKE) test ; cd ../.. ; }
@@ -388,15 +388,15 @@ clean: minizip-clean
 	   example$(EXE) minigzip$(EXE) examplesh$(EXE) minigzipsh$(EXE) \
 	   example64$(EXE) minigzip64$(EXE) \
 	   infcover \
-	   libz.* foo.gz so_locations \
+	   libptlibzippy.* foo.gz so_locations \
 	   _match.s maketree contrib/infback9/*.o
 	rm -rf objs
 	rm -f *.gcda *.gcno *.gcov
 	rm -f contrib/infback9/*.gcda contrib/infback9/*.gcno contrib/infback9/*.gcov
 
 maintainer-clean: distclean
-distclean: clean zconf # zconf.h.cmakein
-	rm -f Makefile zlib.pc configure.log
+distclean: clean ptzippyconf # ptzippyconf.h.cmakein
+	rm -f Makefile ptlibzippy.pc configure.log
 	-@rm -f .DS_Store
 	@if [ -f Makefile.in ]; then \
 	printf 'all:\n\t-@echo "Please use ./configure first.  Thank you."\n' > Makefile ; \
@@ -406,26 +406,26 @@ distclean: clean zconf # zconf.h.cmakein
 tags:
 	etags $(SRCDIR)*.[ch]
 
-adler32.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h
-zutil.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)gzguts.h
-gzclose.o gzlib.o gzread.o gzwrite.o: $(SRCDIR)zlib.h zconf.h $(SRCDIR)gzguts.h
-compress.o example.o minigzip.o uncompr.o: $(SRCDIR)zlib.h zconf.h
-crc32.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)crc32.h
-deflate.o: $(SRCDIR)deflate.h $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h
-infback.o inflate.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h $(SRCDIR)inffixed.h
-inffast.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h
-inftrees.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)inftrees.h
-trees.o: $(SRCDIR)deflate.h $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)trees.h
-crc32_vx.o: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)contrib/crc32vx/crc32_vx_hooks.h
+adler32.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h
+ptzippyutil.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)ptzippyguts.h
+gzclose.o gzlib.o gzread.o gzwrite.o: $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)ptzippyguts.h
+compress.o example.o minigzip.o uncompr.o: $(SRCDIR)ptlibzippy.h ptzippyconf.h
+crc32.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)crc32.h
+deflate.o: $(SRCDIR)deflate.h $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h
+infback.o inflate.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h $(SRCDIR)inffixed.h
+inffast.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h
+inftrees.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inftrees.h
+trees.o: $(SRCDIR)deflate.h $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)trees.h
+crc32_vx.o: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)contrib/crc32vx/crc32_vx_hooks.h
 
-adler32.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h
-zutil.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)gzguts.h
-gzclose.lo gzlib.lo gzread.lo gzwrite.lo: $(SRCDIR)zlib.h zconf.h $(SRCDIR)gzguts.h
-compress.lo example.lo minigzip.lo uncompr.lo: $(SRCDIR)zlib.h zconf.h
-crc32.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)crc32.h
-deflate.lo: $(SRCDIR)deflate.h $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h
-infback.lo inflate.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h $(SRCDIR)inffixed.h
-inffast.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h
-inftrees.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)inftrees.h
-trees.lo: $(SRCDIR)deflate.h $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)trees.h
-crc32_vx.lo: $(SRCDIR)zutil.h $(SRCDIR)zlib.h zconf.h $(SRCDIR)contrib/crc32vx/crc32_vx_hooks.h
+adler32.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h
+ptzippyutil.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)ptzippyguts.h
+gzclose.lo gzlib.lo gzread.lo gzwrite.lo: $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)ptzippyguts.h
+compress.lo example.lo minigzip.lo uncompr.lo: $(SRCDIR)ptlibzippy.h ptzippyconf.h
+crc32.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)crc32.h
+deflate.lo: $(SRCDIR)deflate.h $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h
+infback.lo inflate.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h $(SRCDIR)inffixed.h
+inffast.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inftrees.h $(SRCDIR)inflate.h $(SRCDIR)inffast.h
+inftrees.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)inftrees.h
+trees.lo: $(SRCDIR)deflate.h $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)trees.h
+crc32_vx.lo: $(SRCDIR)ptzippyutil.h $(SRCDIR)ptlibzippy.h ptzippyconf.h $(SRCDIR)contrib/crc32vx/crc32_vx_hooks.h
